services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dolidb
            MYSQL_USER: dolidbuser
            MYSQL_PASSWORD: dolidbpass

        volumes:
            - /home/dolibarr_mariadb:/var/lib/mysql

    Dolibarr:
        image: dolibarr/dolibarr:latest
        container_name: dolibarr
        environment:
            DOLI_DB_HOST: mariadb
            DOLI_DB_NAME: dolidb
            DOLI_DB_USER: dolidbuser
            DOLI_DB_PASSWORD: dolidbpass
            DOLI_URL_ROOT: "http://0.0.0.0"
            DOLI_ADMIN_LOGIN: "admin"
            DOLI_ADMIN_PASSWORD: "admin"
            DOLI_CRON: 0
            #Import des données test (lors que le  paramètre est a 1)
            DOLI_INIT_DEMO: 1
            DOLI_COMPANY_NAME: XXX-SAE51
            DOLI_ENABLE_MODULES: Societe, Import

        ports: 
            - "8085:80"
        links:
            - mariadb
        volumes:
            - /home/dolibarr_documents:/var/www/documents
            - /home/dolibarr_custom:/var/www/html/custom

